name: Android CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    - name: set up JDK 17 for sdkmanager
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    - name: Install Android SDK packages
      run: echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-21" "build-tools;21.1.2"

    - name: set up JDK 8 for build
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    - name: Install system dependencies (for 32-bit aapt)
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y zlib1g:i386 libc6:i386 libstdc++6:i386

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/**/*.apk
